// WEGORA Hub Landing Page Illustrations
export { HubHeroIllustration } from './HubHeroIllustration';
export { ServiceFlowDiagram } from './ServiceFlowDiagram';
export { EigentuemerFlowDiagram } from './EigentuemerFlowDiagram';
export { AllInOneProblemsIllustration } from './AllInOneProblemsIllustration';
export { WegoraModularIllustration } from './WegoraModularIllustration';
export { ServiceAccountingIllustration } from './ServiceAccountingIllustration';
export { ServiceNebenkostenIllustration } from './ServiceNebenkostenIllustration';
export { ServiceDokumenteIllustration } from './ServiceDokumenteIllustration';
export { ServiceVorgaengeIllustration } from './ServiceVorgaengeIllustration';
export { ServiceNebenkostenCheckIllustration } from './ServiceNebenkostenCheckIllustration';
export { ServiceWEGIllustration } from './ServiceWEGIllustration';
export { DataIntegrationIllustration } from './DataIntegrationIllustration';
export { TransitionVisualization } from './TransitionVisualization';
